version: "3.9"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "7000:7000"
      - "8000:8000"
    depends_on:
      - redis
